from sqlmodel import SQLModel, Field


class Subreddit(SQLModel, table=True): ...


class Submission(SQLModel, table=True): ...


class User(SQLModel, table=True): ...


class Comment(SQLModel, table=True): ...
