from sqlmodel import SQLModel, Session, Field, create_engine


class Subreddit(SQLModel, table=True): ...


class Submission(SQLModel, table=True): ...


class User(SQLModel, table=True): ...


class Comment(SQLModel, table=True): ...
